"""
main.py — Entry point for the Agentic Research Assistant API.

WHAT THIS FILE DOES:
  This is the thin "entry point" that wires everything together.
  It follows the same pattern as Lecture 18's main.py:

    1. Create the FastAPI app
    2. Add middleware (CORS)
    3. Register the router from routes.py
    4. Define the lifespan (startup / shutdown logic)

  All endpoint logic lives in app/api.py.
  All route declarations live in app/routes.py.
  All agent logic lives in app/agent.py.

NEW IN LECTURE 19 (vs Lecture 18):
  - LangGraph agent (built once at startup, reused for every request)
  - SQLite database (initialized at startup via init_db())
  - SSE streaming endpoint (POST /research)
  - PDF generation endpoint (GET /history/{id}/pdf)
  - History management (GET/DELETE /history)

HOW TO RUN:
    cd lecture_20_agentic_researcher/backend
    uvicorn main:app --reload --port 8002

  Then open the frontend:
    cd lecture_20_agentic_researcher/frontend
    npm install && npm run dev
    → http://localhost:5173

API DOCS (auto-generated by FastAPI):
    http://localhost:8002/docs
"""

import logging
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Load .env file BEFORE importing app.config — config reads env vars at import time
load_dotenv()

from app.agent import build_agent
from app.api import app_state
from app.config import settings
from app.database import init_db
from app.routes import router

logging.basicConfig(level=logging.INFO, format="%(levelname)s | %(message)s")
logger = logging.getLogger(__name__)


# ── Lifespan (startup / shutdown) ─────────────────────────────────────────────
# The lifespan context manager runs:
#   - BEFORE yield: startup code (build agent, init DB)
#   - AFTER yield:  shutdown code (cleanup)
# FastAPI calls this automatically when the server starts and stops.

@asynccontextmanager
async def lifespan(app: FastAPI):
    # ── Startup ───────────────────────────────────────────────────────────────
    if not settings.openai_api_key:
        raise RuntimeError("OPENAI_API_KEY environment variable is required. Add it to .env")

    if not settings.tavily_api_key:
        logger.warning("TAVILY_API_KEY not set — web search will fail at runtime")

    # Initialize SQLite database (creates the file and table if not exists)
    logger.info("Initializing SQLite database...")
    init_db()

    # Build the LangGraph agent (compiles the graph, creates the LLM clients)
    logger.info("Building research agent...")
    app_state["agent"] = build_agent(openai_api_key=settings.openai_api_key)
    logger.info("Research agent ready. Server is up at http://localhost:8002")
    logger.info("API docs: http://localhost:8002/docs")

    yield  # Server is now running and accepting requests

    # ── Shutdown ──────────────────────────────────────────────────────────────
    app_state.clear()
    logger.info("Server shut down.")


# ── FastAPI app ────────────────────────────────────────────────────────────────

app = FastAPI(
    title="Agentic Research Assistant — Lecture 19",
    description=(
        "Give the agent a topic. It validates the topic, plans its research strategy, "
        "searches the web (up to 20 URLs), optionally searches a local knowledge base, "
        "and writes a structured report. "
        "Every step streams to the browser in real time via Server-Sent Events (SSE)."
    ),
    version="2.0.0",
    lifespan=lifespan,
)

# CORS (Cross-Origin Resource Sharing): allows the frontend (http://localhost:5173)
# to call the backend API (http://localhost:8002).
# In production you'd restrict allow_origins to your domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# Register all routes from routes.py
app.include_router(router)


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import uvicorn
    # reload=True watches for file changes and restarts automatically (dev mode only)
    uvicorn.run("main:app", host="0.0.0.0", port=settings.port, reload=True)
